from textwrap import dedent
from django.test import TestCase
from django.db import models
from django_model_docs.serializers.app_serializer import AppSerializer


class TestAppSerializer(TestCase):
    def test_works_as_expected(self):
        """Serializes a model correctly"""

        serializer = AppSerializer()

        self.maxDiff = None

        self.assertEqual(
            serializer.markdown("demo_django_app"),
            (
                "# `demo_django_app`` app`\n"
                + "\n"
                + "_This file was auto-generated Django Model Docs Generator.  Do not edit this file directly._\n"
                + "\n"
                + "None\n"
                + "\n"
                + "## `person` model\n"
                + "\n"
                + "Person(id, first_name, last_name)\n"
                + "\n"
                + "|    Field   |Description|  Data type |Nullable|Default|\n"
                + "|------------|-----------|------------|--------|-------|\n"
                + "|    `id`    |           |BigAutoField|  False |   -   |\n"
                + "|`first_name`|           |  CharField |  False |   -   |\n"
                + "| `last_name`|           |  CharField |  False |   -   |\n"
                + "\n"
            ),
        )
